baseURL = "https://fishandrice000000.github.io/"
languageCode = "zh-cn"
title = "åƒé±¼åƒç±³ChMiğŸ“"
theme = "PaperMod"
enableGitInfo = true
timeZone = "Asia/Shanghai"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto" 

  [params.profileMode]
    enabled = true
    title = "åƒé±¼åƒç±³ChMiğŸ“" 
    subtitle = "ä¸€èˆ¬é€šè¿‡ä»£ç ä½æ‰‹"
    imageUrl = "/avatar.png"
    imageWidth = 120
    imageHeight = 120
    
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/fishandrice000000"

  [params.assets]
    favicon = "/favicon.ico"
    favicon16x16 = "/favicon-16x16.png"
    favicon32x32 = "/favicon-32x32.png"
    apple_touch_icon = "/apple-touch-icon.png"

[[menu.main]]
  identifier = "archives"
  name = "Blogs"
  url = "/blogs/"
  weight = 10 

[[menu.main]]
  identifier = "search"
  name = "Search"
  url = "/search/"
  weight = 20 

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 30

